### ISSUE TITLE
Hosting backend application

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#28]
## Description
host backend application to make it accessible over the internet.

## Tasks
- [ ] Choose a hosting service (e.g., Render).
- [ ] Set up the hosting environment.
  - [ ] Configure the server to run the backend application.
  - [ ] Set environment variables.
  - [ ] Configure the database connection.
- [ ] Deploy the backend application.
- [ ] Test the deployment to ensure it works correctly.

## Acceptance Criteria
- The backend application should be accessible over the internet.
- Environment variables should be securely managed.
- Database connections should be correctly configured.
- The deployment should be tested and verified to be working.

**Comment by Rofiatmuritala** [comment]
I will take up this task
