### ISSUE TITLE
 Signup functionality 

### ISSUE THREAD

**Issue by emmanuelAkpe** [mestafrica/digitizing-the-ges-curriculum#31]
## Description
Implement the signup functionality for new users to create accounts.

## Tasks
  - [ ] Create user accounts and store them in the database.
- [ ] Handle signup responses in the frontend.
  - [ ] Provide feedback to users upon successful or failed signup.

## Acceptance Criteria
- Users should be able to create new accounts.
- User data should be securely stored in the database.
- Proper error messages should be displayed for failed signup attempts.

**Comment by iamatinad** [comment]
@emmanuelAkpe please I'd like to pick this up

**Comment by emmanuelAkpe** [comment]
great . It has been assigned to you
